# Generated by Django 4.0.1 on 2022-02-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_email_remove_profile_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='s_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
