# Generated by Django 4.0.1 on 2022-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_s_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thought',
            field=models.TextField(default=''),
        ),
    ]
